#ifndef TESTPLUGIN1_GLOBAL_H
#define TESTPLUGIN1_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TESTPLUGIN1_LIBRARY)
#  define TESTPLUGIN1SHARED_EXPORT Q_DECL_EXPORT
#else
#  define TESTPLUGIN1SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TESTPLUGIN1_GLOBAL_H
